Name = input("Enter Your Name: ")
Age = int(input("Enter Your Age: "))
Dept = input("Enter Your Dept: ")
College=input("Enter Your College name: ")
# print("your name is ",Name)
# print("your age is",Age)
# print("dept of studing",Dept)
# print("college studing is",College)
print(f"your name is {Name} {Age} year old studing BE {Dept} at {College} ")